### ISSUE TITLE
Ability to capture/decrypt over ESP in ipsec

### ISSUE THREAD

**Issue by jmordica** [irontec/sngrep#101]
Do you guys have any plans to do something similar to wireshark that would allow us to grab the leg of the call/signaling that goes to and from an IPSec tunnel?

Thanks!

**Comment by jmordica** [comment]
Actually, I'm not sure if it would need to decrypt anything because it's running on the same box as the ipsec tunnel is set on. The reason I say this is because sngrep shows me the signaling coming from the ipsec tunnel IP on an incoming call but it does not on outgoing calls. It's a bit strange. Let me know if you need additional information.

Thanks.

**Comment by Kaian** [comment]
Hi @jmordica 

Current priorities in mind are improving interface, RTCP parsing,capture and HEP in that order.
You can check [TODO](https://github.com/irontec/sngrep/blob/master/TODO) of some ideas I'm planning. There's a lot of documentation outdated too that needs care.

The main reason I am not putting too many efforts in decrypting is that if sngrep (or other tool) can decrypt it, it's not *really* secure. And I don't think we should encourage _unsecure security_. That was another reason why we thought HEP support as an alternative. Many proxys and B2BUA that support HEP can resend decrypted data to a local box port, allowing debugging secure ciphers (with perfect forward secrecy) connections. At least I hope so.

The other reason is that we don't want to make sngrep a cracking tool, where if someones gets your private key somehow, even old captured data can be decrypted.

I leave TLS decrypt as is, because may be useful for someone that doesn't support new TLS ciphers, but I highly recommend to look for another way to debbug it (eg hep as I mentioned before). Also, the openssl/gnutls dependency may become useful if we implement HEP over SSH or something like this.

Anyway thanks for asking so I can show my perfective of current sngrep decrypt mode :)

Best regards

**Comment by jmordica** [comment]
Hi thanks for the reply. Makes sense to me. I will take the hep route on this one :)

Thanks!
