### ISSUE TITLE
Crash issue with SIP TCP fragment

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#106]
Crash issue with SIP TCP fragment

I had mailed fragment.pcap

**Comment by Kaian** [comment]
Confirmed.

The problem was we were using TCP PSH flag assuming is set when a packet is ready or is the last segment, which seems totally wrong. We will remove that condition and just validate the received payload.

Thanks for reporting, you're the best bug finder!!

**Comment by michael2009** [comment]
no crash now . but loss some tcp packet

**Comment by Kaian** [comment]
Hi michael!

The pcap you sent me has a 4 byte packet between SIP messages just with CRLFCRLF (0x0d0a0d0a) codes that was breaking the assembly process (next packet was not detected as SIP because it had that 4 bytes before the REGISTER word method).

I have improved the detection function to ignore that, but there are still limitations in TCP:

 * Packets won't be parsed if one packet has more than one SIP messages. We can merge multiple packets into one big SIP packet, but we don't split packets into several messages (or partial messages).
 
 * Packet won't be detected as SIP if the first segments doesn't match a SIP request o response format. That means that if we receive a first small TCP fragment with 20 bytes followed by a bigger packet with the rest of the payload, both will be ignored.

* More than two unsorted tcp fragments are not assembled. That means that we assembly 2 unsorted fragments, or infinite sorted fragments, but if there are multiple fragments and they have random orders, most probably they won't be displayed.

We rarely use TCP SIP transport, so there will be some bugs and incompletes features. The only TCP tests I do are the pcaps you provide me, so I may be working only under certain conditions.

Anyway, any bug report is still appreciated!!
Thanks!
