### ISSUE TITLE
SIP 480 not captured

### ISSUE THREAD

**Issue by davemidd** [irontec/sngrep#116]
Using 1.3.1
INVITE ->
100 <-
180 <-
480 <-
ACK ->

sngrep doesn't display the 480 in the UI and it's not in the saved cature (but is in a standalone capture).

**Comment by Kaian** [comment]
Hi  @davemidd 

The missing message must have something special to be avoided somehow in the capture. If you can provide a PCAP file with the message that is not displaying I can debug the reason.

I have done some tests with 480 and they are displayed as expected, so there is nothing wrong with the response code itself.

![sngrep-116](https://cloud.githubusercontent.com/assets/800069/14958468/3c448c4c-108b-11e6-8e7c-5202e3761e3f.png)


Thanks for reporting!

**Comment by Kaian** [comment]
Thanks for the testing pcap.

The problem was the 480 has no Reason text and the SIP parser failed to get the code. According to the RFC:

`Status-Line  =  SIP-Version SP Status-Code SP Reason-Phrase CRLF`

As Reason-Phrase in the Status-Line of the responses can be a custom message, so I assume that an empty message is also correct.

Thanks for reporting!!
