### ISSUE TITLE
Availability on OpenWRT/LEDE

### ISSUE THREAD

**Issue by diizzyy** [irontec/sngrep#151]
Hi,

If you want to include this info it's also available on OpenWRT/LEDE nowdays.
https://github.com/openwrt/packages/blob/master/net/sngrep/Makefile

Great work on this app!

Best regards,
Daniel

**Comment by nshopik** [comment]
`sngrep` and `sipgrep` are different projects actually

**Comment by Kaian** [comment]
Hehe, I also was surprised at first, but it seems just a typo, because [the link](https://github.com/openwrt/packages/tree/master/net/sngrep) for sngrep also exists 0:-))

If you suggest me where should update; or better, if you want to update the wiki (which anyone in the community can!) feel free to do it so!

Thanks for the input!

**Comment by diizzyy** [comment]
Sorry! My bad! :-)
Kaian, you're absolutely correct =)

**Comment by Kaian** [comment]
I think the package install method for OpenWRT is  `opkg install sngrep`
Does it require any repository configuration? I will update the wiki with that info ;-)

Thanks!

**Comment by diizzyy** [comment]
That's all you need to do.
It's not backported so it's only available on trunk/head for now.
