### ISSUE TITLE
Filter by call state

### ISSUE THREAD

**Issue by kronolovic** [irontec/sngrep#153]
Would like to be able to filter "calls" by call state, for example "Completed".

I often look att big .pcap:s with large amounts of calls where the answered ones are the only ones that interest me.

**Comment by Kaian** [comment]
Hi @kronolovic

Callstate is something that we get analyzing groups of packets, so probably a capture filter won't be possible (as they filter out packet by packet)

The current working option is to load the pcap (probably with --calls flag) and add the column to the list of displayed (the default column layout aldready has it). Then press / and type COMPL in the display filter input.

This is not optimal, because unlike capture filters, display filters are slow and dont reduce anything the resources used by sngrep, but well...

Regardw

**Comment by kronolovic** [comment]
Thank you for the tip. I'll give it at shot next time.

**Comment by Kaian** [comment]
Ok!

I will close this then, feel free to reopen if you have any other question!
