### ISSUE TITLE
Segfault in 1.4.0

### ISSUE THREAD

**Issue by kikohnl** [irontec/sngrep#157]
Not sure why this is happening, but maybe this gdb output will help.

[gdb.txt](https://github.com/irontec/sngrep/files/570208/gdb.txt)

Thanks

**Comment by Kaian** [comment]
Hi @kikohnl 

Thanks for the backtrace. Not sure what make it crash, because the gdb trace shows that the two threads are waiting for data, no processing it:
  - Capture thread is in libpcap territory waiting for a new packet to be readed
  - UI thread is in libncurses territory waiting for an user input key

The only possible crash that we can generate from our code is to corrupt memory so libraries don't work properly. In fact this lines of the trace are quite strange:

```
#3  0x00000000004041ad in capture_thread (info=0xfffffffffffffe00) at capture.c:779
        capinfo = 0xffffffffffffffff
```

Does this crash happens always on startup? or during a normal run?

Thanks for the info and reporting!!

**Comment by kikohnl** [comment]
Kaian,

Thanks for a fantastic tool!

The segfault is random, but normally happens at the end of a call, right after the last  ACK

**Comment by Kaian** [comment]
Can be this crash reproduced in offline mode?

If you capture with other tool while you use sngrep and it crashes, and you open that .pcap file, it also crashes? It helps a lot debugging this kind of problems.

Thanks for the info!

**Comment by Kaian** [comment]
Is there any extra information on this crash? 

Thanks in advance!

**Comment by Kaian** [comment]
Closed due to lack of activity.

Feel free to reopen if you have any new input!
