### ISSUE TITLE
why my call flow window has no arrows, only qqqqqq

### ISSUE THREAD

**Issue by zhulizhong** [irontec/sngrep#158]
Hello:
I install te sngrep and can get the data, but the call flow window does not show like your samples, my windows only show qqqqqqqqqqqq and no double arrows. Any one can tell me how to show with double arrows instead of qqqqqqqqqq. 
![sip-sn](https://cloud.githubusercontent.com/assets/13025117/20201625/7a94107a-a7f4-11e6-981d-2f1b6b21d6eb.png)

**Comment by nshopik** [comment]
Change terminal encoding to UTF-8

**Comment by Kaian** [comment]
Hi @zhulizhong !

Its quite common, check #26 or #36 (spanish) for some hints of fixing this.
The problem is a mix between your local enviroment encodings and your terminal emulator. The UTF-8 arrows and lines are more beautiful that using plain ASCII chars, but you can disable them exporting an environment var (or setup your encodings to make them work).

Best regards!

**Comment by davidwjacob** [comment]
I am having a problem kind of like this. i use ansi emulation on securecrt and the terminal is all messed up.

![capture](https://cloud.githubusercontent.com/assets/13281170/20229191/175a84c4-a823-11e6-98fb-9913224ba2bb.JPG)

do i have to change my term emulation get it to work correctly, sorry if this has been answered before or is a noob ques. cant seem to find a answer.

**Comment by zhulizhong** [comment]
thanks, I change to ISO-8859, it works!

**Comment by zhulizhong** [comment]
thanks, I change to ISO-8859, it works!

**Comment by zhulizhong** [comment]
thanks, I change to ISO-8859, it works!

**Comment by Kaian** [comment]
Nice!

@davidwjacob I have been trying to reproduce your problem with securecrt without success. I have changed Terminals to ANSI, Xterm and Linux and all seems to work as expected. The problem in the screenshot is something that I have never seen, but If you find that other tools with ncurses (for example, htop or mc) work ok, feel free to open an issue and will try to look where the problem is.

Thanks!
