### ISSUE TITLE
can not parse  large udp packet

### ISSUE THREAD

**Issue by andy9100** [irontec/sngrep#164]
[video4.zip](https://github.com/irontec/sngrep/files/683767/video4.zip) 
thanks

**Comment by Kaian** [comment]
Hi @andy9100 

Thanks for reporting and the test pcap, it helps a lot!

This has been fixed in the latest `master` commit. The problem was the packet size calculation when assembling IP fragments. It was not properly calculated for packets with more than 2 fragments (your initial INVITE has 3 fragments!).

Best regards,
Kaian

**Comment by andy9100** [comment]
great job! thank you. you make a great project, save me lot of time.

**Comment by Kaian** [comment]
You welcome!

Thanks for testing the fix. Closing this.
