### ISSUE TITLE
No "Settings" key help shown in help screen

### ISSUE THREAD

**Issue by abelbeck** [irontec/sngrep#169]
When typing ```h``` or ```?``` to get the help screen, there is no listing for "Settings".

The ```F8``` is listed, but ```F8``` seems to be defined twice in ```src/keybinding.c```
```
{ ACTION_TOGGLE_SYNTAX,  "togglesyntax", { KEY_F(8), 'C' }, 2 },
...
{ ACTION_SHOW_SETTINGS,  "settings",     { KEY_F(8), 'o', 'O' }, 3 },
```
The help list in ```src/curses/ui_call_list.c``` shows:
```
mvwprintw(help_win, 20, 2, "F8/c        Turn on/off window colours");
```

May I suggest you change the help screen:
```
- mvwprintw(help_win, 20, 2, "F8/c        Turn on/off window colours");
+ mvwprintw(help_win, 20, 2, "F8/o        Edit Settings");
```
which would be consistent to the lower, main label ```F8 Settings```

I realize you are limited to your help screen size.

**Comment by Kaian** [comment]
Hi @abelbeck

As you mention, help screens have a fixed size because I didn't want to include all the bindins, just the most useful or common. But we can add new rows if we think they will be useful :-D

The change you propose seems totally fine to me, if you are willing to PR, it would be great, otherwise it'll have to wait as right now I'm on holidays.

Thanks for the feedback!!

**Comment by abelbeck** [comment]
Added PR #170 

I used "Show Settings" instead of the "Edit Settings" I originally proposed, seemed more consistent.

**Comment by Kaian** [comment]
I also think it represents more what the key does.

Thanks @abelbeck!
