### ISSUE TITLE
Segfault 1.4.2

### ISSUE THREAD

**Issue by SebastianThorn** [irontec/sngrep#177]
Hi, we recently upgraded from v0.2/0.3 to 1.4.2,
now I'm getting segfaults very often, this mostly happens when i press F5 to refresh.
Got 2 servers that I'm running this on, the segfault occurs on both machines from time to time.
How do i help out best, to gather useful information?

```
# dpkg -l | grep sngrep
ii  sngrep                             9999~20170310.98~9b9340c+wheezy         amd64        Ncurses SIP Messages flow viewer

# sngrep -V
sngrep - 1.4.2
Copyright (C) 2013-2016 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with GnuTLS support.
 * Compiled with Wide-character support.
 * Compiled with Perl Compatible regular expressions support.
 * Compiled with IPv6 support.
 * Compiled with EEP/HEP support.
```

Thank you for an awesome tool!
Br Sebastian Thörn

**Comment by Kaian** [comment]
Hi @SebastianThorn 

Thanks for reporting! The was a problem in our CI and the latest packages (generated with each commit) was being published in the repos! That's the reason you have 9999 in your package version. Sorry for that and glad you've reported, otherwise I wouldn't notice.

If you have installed this untested versions, you can reinstall the original 1.4.2 version by specifing the version in the command line, for example for wheezy:

```
# apt-get update
# apt-get install sngrep=1.4.2+wheezy
```

In the other hand, you have probably discovered a bug that happens in the not yet released sngrep. I will try to reproduce this problem by myself now that you have suggested that the problem can be related with clearing the call list. If I'm unable to reproduce it maybe I will come back to request you some traces with a special version of sngrep that has debugging enabled.

Thanks again!

**Comment by SebastianThorn** [comment]
Sound like a plan!

**Comment by Kaian** [comment]
I was unable to reproduce this so I think I will release and cross fingers... :sweat_smile: 

Thanks as always for taking the time to notifing this problem!
