### ISSUE TITLE
Capture limit value

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#179]
Few things that need to be clarified regarding the limit (`-l`) parameter.

1) I think it should require the argument but it has `no_argument` flag:

  * https://github.com/irontec/sngrep/blob/master/src/main.c#L149

2) Capturing without a limit

Apparently if set to 0, there should be no check in the limit for capturing packets:

  * https://github.com/irontec/sngrep/blob/master/src/capture.c#L241

But if set to 0, then the parsing of the argument will result in a failure to start, because atoi() will return 0:

  * https://github.com/irontec/sngrep/blob/master/src/main.c#L215 

Moreover, it seems that some hash table is not going to be allocated properly:

  * https://github.com/irontec/sngrep/blob/master/src/sip.c#L157

Overall, I was looking for what's the proper way to run with no limit in capture-only mode with no interface (-N). I think it works with -R, but somehow the limit parameter is confusing, especially due to its check in the code if it is 0 or not to apply the limit.

**Comment by Kaian** [comment]
Hi @miconda!

1. Yep, that's a bug. Argument is a _must_.
2. Capturing without limit was requested some time ago (#94) but I am not sure if its a good idea in sngrep. One of the bad things of how sngrep works is that stores everything in memory, without any memory manager that control how much memory it eats. That means that if somebody leaves an unattended sngrep in a production environment, it may cause `oom`. The partial solution to this was to implement a rotation system, so we eat memory with a degree of control, free'ing the old dialogs when the limit is reached. If that limit is too high (or there is no limit), it's useless.

The limit 0 not working is an unintentional behaviour that matches the intentional desire of not allowing unlimited captures. But both agree it should be checked and returned as invalid value while parsing the command line args.

So I think that in order to allow unlimited capture, I have to first implement some memory manager and memory strategy (rotate when mem limit has been reached, ignore new, etc)

Thanks for the feedback!

**Comment by miconda** [comment]
As for 2) -- it is fine, at least for me, to have the `unlimited capture` as a combination of `-l` and `-R`, but it felt like confusing when reading the code by the check at the rotation. So maybe some clarifications need to be done in the docs/params description.

This is needed in combination with -N, when I want to capture in a file or send out via HEP/EEP, so no need at all to store in memory everything.

**Comment by Kaian** [comment]
I have fixed the problem for 1). I always use the `-l` version that uses the short options string (which has `l:` forcing the option to have argument). While using the long version of the argument, your pointed bug arises.

```
$ sngrep --limit
segmentation fault (core dumped)  src/sngrep --limit
```

For 2) I have updated the `man sngrep` options to include a more descriptive text for `-l` argument. This man pages require a lot of work (long options are not even mentioned!), but any contribution is appreciated. I'm far from good at writting english descriptions.

Also, as mentioned in the other issue, when -N option is used, only the required basic data of the dialog is stored, just to match the following messages of the same dialog. Packet contents or extra info are free'd, reducing memory usage. Most of the times, I still recommend to use an expert tool like captagent for capturing during long periods :smile: 

Thanks a lot for the feedback @miconda !!

**Comment by miconda** [comment]
Thanks! As said, I am fine with this solution, if the `-R` is enough to have smooth running over long time. Probably all is quite safe for active calls, and `-l` can be used to increase the size of capture ring.

This issue can be even closed. Eventually add to your/sngrep todo list a goal to simplify/optimize the long running use case, if you think something can be improved.

I agree that the use of captagent might be better, but it is rather complex as it can handle many other protocols, while sngrep is very simple to use for SIP and typically installed for normal use of seeing the traffic in real time by admins. There is also sipgrep, therefore all this eventual enhancement can seat as a goal in todo.

**Comment by Kaian** [comment]
So be it. I don't like limiting things, even if it may be dangerous :)
Most probably I won't be satisfied until I remove the limit hehe

Thanks again!
