### ISSUE TITLE
sngrep crashes with segmentation fault

### ISSUE THREAD

**Issue by billsimon** [irontec/sngrep#186]
`May 11 21:30:17 dev-sipproxy01 kernel: [282543.007817] sngrep[19890]: segfault at 7f08c402f2b4 ip 000000000040df06 sp 00007f08ca119cb0 error 4 in sngrep[400000+26000]
`

Sometimes this happens after monitoring traffic for a minute, other times it runs for hours before crashing. How can I debug?

Version 1.4.3 (updated today) built with `--with-openssl` and `--enable-eep`

**Comment by billsimon** [comment]
I ran in gdb and got a little more information.

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5906700 (LWP 20171)] 
rtp_check_packet (packet=packet@entry=0x7fffe8006b10) at rtp.c:294  
2941:40:                            switch (blk_xr.type) {  
(gdb) bt 
#0  rtp_check_packet (packet=packet@entry=0x7fffe8006b10) at rtp.c:294 
#1  0x0000000000405bc7 in capture_packet_parse (packet=0x7fffe8006b10) at capture.c:735 
#2  0x0000000000405d95 in parse_packet (info=<optimized out>, header=<optimized out>, packet=<optimized out>) at capture.c:324 
#3  0x00007ffff6ada5ea in ?? () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 
#4  0x00007ffff6ade784 in ?? () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8  
#5  0x00007ffff6ae2d5d in pcap_loop () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8     
#6  0x00007ffff68bf064 in start_thread (arg=0x7ffff5906700) at pthread_create.c:309     
#7  0x00007ffff65f462d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111    
(gdb)
```

**Comment by abelbeck** [comment]
@billsimon Just a stab in the dark, how about if you disable packet offload for the interfaces that sngrep monitors. ex.
```
ethtool -K eth0 tso off gso off gro off
```
I have found occasional issues with libpcap and some NIC's with packet offload enabled.

**Comment by billsimon** [comment]
Thanks for the suggestion, but it did not make a difference.

**Comment by Kaian** [comment]
The easiest way to debug is capturing a crashing pcap with a non-parsing tool (tcpdump, ngrep,..) 
 at the same time and trying to open it with sngrep  after the crash. That way we can easily reproduce the crash and test any fix. 

If the data captured its too private so you can not send it to me, I can try to provide some debugging commands for gdb, but makes the whole process a bit more conplicated.

The crash looks like a problem parsing a RTP packet, but it's the first time I see a crash there since a lot of time :-m

Thanks for reporting!!

**Comment by billsimon** [comment]
[crashtest.pcap.gz](https://github.com/irontec/sngrep/files/996150/crashtest.pcap.gz)
This one crashes sngrep.

**Comment by Kaian** [comment]
Hi @billsimon 

Thanks for the testing pcap, it always helps A LOT for debugging crashes.

The problem here is that sngrep is trying to parse SRTCP packets (which are obviusly encrypted) what gives invalid values for length, header type, and so on, making the parser to read memory far from packet payload (and segfaulting).

This code has not been changed in 1.4.3 so this problem should happen in previous versions too.

The latest commit in master works with the provided pcap. Let's hope it fixes the problem!

Thanks for reporting!

**Comment by billsimon** [comment]
Thanks, I tested the new code with some live calls similar to those in the pcap and sngrep did not crash.
