### ISSUE TITLE
EEP/HEP doesn't show up messages

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#193]
Tried EEP/HEP with config below, doesn't seem show up anything for me. I've send privately HEP pcap if that help. Ignore ICMP errors in pcap they are captured when nobody listen on port

```
set eep.listen on
set eep.listen.version 3
set eep.listen.address 127.0.0.1
set eep.listen.port 9061
```

**Comment by Kaian** [comment]
Hi @nshopik !

Is your HEP sender using password?

It seems sngrep is [coded to allow listening HEP without password](https://github.com/irontec/sngrep/blob/master/src/capture_eep.c#L665) but the actual setting _eep.listen.pass_ can not be set to NULL :disappointed: 

This could be easily fixed by changing the [default value of the setting](https://github.com/irontec/sngrep/blob/master/src/setting.c#L87) from "myHep" to NULL.

As a workaround, you can configure sender password and sngrep setting to test if that's the actual problem.

Regards!

**Comment by nshopik** [comment]
Yeah i didn't configure any passwords on HEP sender since I send on loopback. Yeah it would be nice to have ability set it to NULL

**Comment by Kaian** [comment]
This last commit changes de default password value from myHep to empty strings, which according to the output of `sngrep -D` should be considered null.

If you can give it a shot, I will appreciate.

Regards
