### ISSUE TITLE
support include pcap if use archive gzip or bzip2

### ISSUE THREAD

**Issue by thefree** [irontec/sngrep#198]
tcpdump support
```
-z postrotate-command
Used in conjunction with the -C or -G options, this will make tcpdump run " postrotate-command file " where file is the savefile being closed after each rotation. For example, specifying -z gzip or -z bzip2 will compress each savefile using gzip or bzip2.
```
mb add support pcap in archive gzip or bzip2?

**Comment by Kaian** [comment]
Hi, thanks for the suggestions!

If I understand this correctly, you mean running a command after saving packets into a pcap file. 

This could also help with #166 but I am not sure if thia is a good idea. sngrep requires root privileges in a lot of systems in order to open network capture devices, so I've seen it in sudoers file or with suid execution flag. Running commands inside the code may allow non priviliged users to exec any postcommand with root privileges. 

This setting makes more sense for tcpdump, because it can be run for long times while saving múltiples files (and running a command for each one), but sngrep is not designed for long runs and usually you only save one or two files (if any). You'll be just avoiding some keystrokes after closing the program.

Anyway, any kind of comment or feedback from the rest of the community is welcomed.

**Comment by thefree** [comment]
Hi, thanks for the reply.

Apparently I did not clearly express the idea, I'm interested in the possibility of opening a pcap file that was compressed by gzip or bzip2.

There are many files after tcpdump that are compressed to reduce the size.

**Comment by Kaian** [comment]
Hi @thefree 

This is not what you asked for, but the above commit adds support for stdin as input file.
This way you can pipe your input data like this:

```
$ gzip -c tests/aaa.pcap > tests/aaa.pcap.gz
$ zcat tests/aaa.pcap.gz | sngrep -I -
```

You could easily create a zsngrep script 0:)

**Comment by thefree** [comment]
Thank you for the feature

**Comment by systemcrash** [comment]
I think it would not be a bad idea to transparently handle gzip. Many people copy-paste commands, and some scripts are designed to work with `sngrp .... blah` syntax, instead of `gzcat 2-way-normal.pcap | sngrep -I -`

Perhaps a hint could be printed instead of 
`Couldn't open pcap file 2-way-normal.pcap: unknown file format`

Because to identify a gzip format archive does not require parsing more than 2 bytes. sngrep could even redirect a command (or printing something helpful) when detecting gzip to perform not 
`sngrep -I 2-way-normal.pcap`
but
`gzcat 2-way-normal.pcap | sngrep -I -`

**Comment by Kaian** [comment]
I had a similar discussion some time ago about assuming that if only a command line argument was supplied and that was a file, it would probably be a pcap, so we could do the -I argument optional in that case. At the end we added a hint that you've probably seen: _ XXX seems to be a file: You forgot -I flag?_

The error message displayed by sngrep is directly provided by libpcap library that is in charge of handling input files for parsing. The same applies to most of command line errors like filters and device permissions. It would be nice if libpcap could handle compressed formats, that would make all tools using that library automatically compatible instead of implementing detection in each program. There is also the fact that, if we implement gzip detection, there is no reason to not implement bzip, zip, 7z or rar file compression detection. 

For now we will try to imitate the rest of capture tools behavior and reject those files like ngrep, tshark or wireshark does.

Thanks for the feedback and suggestions!
