### ISSUE TITLE
maybe protocol abstraction layer? other protocols?

### ISSUE THREAD

**Issue by cypa** [irontec/sngrep#216]
Hi, sngrep is very good!
And how do I add other protocols like IAX2, HTTP etc.?
Maybe use some sort of DSL for protocol description?

**Comment by Kaian** [comment]
Hi @cypa 

There is no plans to add complexity in sngrep to support protocols other than SIP/SDP/RTP, mainly because we rearely found ourselfs debugging that ones. Someone also requested Verto in IRC, but we prefer to focus our little time to make work just the couple of protocol we need. At the end, the _s_ of _sngrep_ stands for SIP :)

Thanks for your feedback!

**Comment by cypa** [comment]
I agree, but simple DSL would also allow many users with pecular need (non-RFC features, weird SIP-devices you know) tune sngrep to fit their needs without digging into c code. That is my goal ...

**Comment by nshopik** [comment]
Its rather big task you asking, unless you are willing to write/maintain code I doubt it will happen. 

Also if you need console ncurses-like tool for http look for `mitmproxy`
