### ISSUE TITLE
can´t send the packets to HOMER

### ISSUE THREAD

**Issue by Outconcert** [irontec/sngrep#228]
Hello,
 I have these problem:

[root@localhost ~]# sngrep portrange 5060-5061 -k ./privkey.pem -H udp:192.168.0.108:9060 -q
sngrep is not compiled with SSL support.

I install sngrep whith installed by packages.

Yo have fix issue?

Thanks

Jesus

**Comment by Kaian** [comment]
Hi @Outconcert 

can you provide the output of `sngrep -V`?

I assume you are using [these](https://github.com/irontec/sngrep/wiki/Installing-Binaries#centos--fedora--rhel) binaries for CentOS, RHEL or Fedora. As you see documented in the second line of that section, those binaries are compiled without SSL support..

We discourage the use of SSL decrypting because only [a couple of ciphers](https://github.com/irontec/sngrep/issues/48) are supported. If you use those ciphers and still want to try, you have to do your own compilation following [building instructions](https://github.com/irontec/sngrep/wiki/Building)

Regards!
