### ISSUE TITLE
[feature-request] Add --method-filter as cli parameter

### ISSUE THREAD

**Issue by samael33** [irontec/sngrep#229]
Idea is to have quick select filter by method on startup.
Like 
sngrep -mf INVITE,SUBSCRIBE 
and it will show only INVITE and SUBSCRIBE packets.
Like now I can do filter on INVITE only with sngrep 'INVITE ' but it's not efficient sometimes.

**Comment by Kaian** [comment]
Hi @samael33 

You could more or less archive this using matching expression from command line by only capturing dialogs whose first message starts with INVITE or SUBSCRIBE.

`sngrep "(^INVITE|^SUBSCRIBE)"`

This will be more efficient because, instead of not displaying the dialogs in the list, they will be totally skipped and reduce the memory consumption.

Regards

**Comment by Kaian** [comment]
I hope the sngrep matching string is enough for this task. As mentioned, filtering capture is much more efficient than filtering displayed.

Regards!
