### ISSUE TITLE
[feature-request] Add support for NFLOG link type

### ISSUE THREAD

**Issue by voztovoice** [irontec/sngrep#233]
Hello,

in the SNGREP window always appear traffic from IPs blocked or from IPs not authorized from IPtables. How this kind of traffic is not relevant, is there the possibility to filter it?

Thank you

Regards

**Comment by Kaian** [comment]
Hi @voztovoice 

As you have already notice, libpcap captures raw from the interface, before iptables filtering (on incoming packets) or any packet assembly. As far as I know, there is no tool based on libpcap (ngrep, wireshark, tshark, and so on) that implements this kind of filtering (no iptables integration of any kind) and it looks a bit out of scope. 

Captured packets can be filtered with BPF (Berkeley Packet Filter) expressions, highly recommended on systems with lots of captured packets: you can use network and port ranges to only display the interesting data.

In case you discover this implementation on any capture tool don't hesitate to post any information, I could implement a setting to enable or disable it. Otherwise we will try to behave like the rest of tools of the belt :)

Thanks for reporting!!!

**Comment by voztovoice** [comment]
Hello,
thank you for your response... maybe would be useful filter what I don't want see instead what i want see; is it a possible implement?
Thank you
Regards

**Comment by Kaian** [comment]
Hi !

You can also use [BPF filtes](https://biot.com/capstats/bpf.html) with excluded hosts:

`sngrep host not 8.8.8.8 and host not 4.4.4.4 and host not 104.40.211.35`

Regards!

**Comment by Kaian** [comment]
Hi,

I've been researching a bit on this topic and it seems libpcap supports NFLOG as possible input, so you could duplicate all no rejected traffic and parse those packets. 

https://wiki.wireshark.org/CaptureSetup/NFLOG

To make this possible I have to implement NFLOG linktype and do some testing. I'll rename the issue and post any update here.

Regards!

**Comment by Kaian** [comment]
I have been testing and this is already implemented in https://github.com/irontec/sngrep/commit/49fb3de2423196a8e1c6e5acbbe2ff18dd80b0dc and requested in #222 

In order to capture from a nflog:_x_ device you must add iptables rules to determine which traffic will be displayed, like in the mentioned link.

**Comment by Kaian** [comment]
As mentioned this can be archieved if iptables are configured to do so.  Packet capture is done by libpcap and sngrep can't do anything to select where layer packets are captured.

Regards!
