### ISSUE TITLE
sngrep pcap issue - Packet size limited during capture: SIP truncated

### ISSUE THREAD

**Issue by lexxixc** [irontec/sngrep#238]
I'm using sngrep on FreeBSD 9.3 machine but when i open captured file in wireshark i see SIP INVITE truncated wtih message: [Packet size limited during capture: SIP truncated]. 
sngrep was executed with -d bce0 -O try.pcap host <ip> command
I searched over help documentation but did not find any parameter to increase the packet size filter during the capture in sngrep (like -s parameter in tcpdump).
Please advice how can i capture with sngrep without truncating the messages.

**Comment by Kaian** [comment]
Hi @lexxixc 

The setting you mention from tcpdump is internally set by sngrep to a quite high value in https://github.com/irontec/sngrep/commit/9f0600c96d69ec16d69c5eadd57569c1a3b9bb98

This was detected and fixed in #150 

How many bytes are captured?  What's your sngrep versión?

Thanks for reporting!!

**Comment by lexxixc** [comment]
Thank you for fast feedback and sorry for bothering you without checking the version first. I was sure the version is latest on that machine, but in fact it was old - 1.3.1
The fix you mentioned was not there so I installed the lastest 1.4.5 and it is working fine now. Thanks!

**Comment by Kaian** [comment]
No problem! Thanks to you for the feedback :+1:
