### ISSUE TITLE
Help needed for TLS

### ISSUE THREAD

**Issue by astrakid** [irontec/sngrep#256]
hi,
I am using sngrep with -.k <keyfile.pem> but i don't get any callflows or registrations shown in sngrep. I restarted asterisk to ensure that the TLS handshake is seen by sngrep, but nevertheless I don't see anything.
Is there anything I can do to debug the issue? I think it is not an issue with sngrep, but with my configuration (asterisk is running locally as sngrep does) or on layer 8...
regards,
andre

**Comment by Kaian** [comment]
HI @astrakid !!

Currently sngrep only supports 2 ciphers (see  #214 for example). You also have to all packets since initial TCP connection, so restarting asterisk may help with that.

You can also try other tools to check if your connection can be decrypted (like ssldump or wireshark) or attach  some testing data (a pcap and a temporal priv key) if you want me to debug it.

Thanks!

**Comment by astrakid** [comment]
thanks a lot, finally i was able to go for your approach. I think th eissue is that the SSL-handshake in my case is not successful. So this is not "your" issue. thx a lot again.
