### ISSUE TITLE
Please describe how sngrep decide  what  RTP belongs  to this  conversation 

### ISSUE THREAD

**Issue by gudge25** [irontec/sngrep#257]
https://i.imgur.com/ltxW0jo.png
(why there is more than 2 RTP on  right side)

**Comment by Kaian** [comment]
Hi @gudge25 

If I recall it correctly, sngrep creates stream structures based on SIP messages with SDP. This streams have 3 key values: Source Address (ip + port), Destination Address (ip + port) and Format (g711a, g711u, and so on). When a SDP is parsed, sngrep creates a rtp stream and set destination ip (taken from SIP message) and destination port (taken from SDP connection line).  Once a RTP packet is received, it looks for a stream that have its destination address and completes the rest of the data (source address and format) and a _reverse_ stream is created with the same data and swapped src/dst addresses.

From the image you attached, the right side has four streams, whose destination ports should match some of the call SDPs. I can not tell exactly because I can not check the SDPs (you can display more information by pressing _D_ keybinding a couple of times)
