### ISSUE TITLE
Crash with duplicate packets: stack smashing detected

### ISSUE THREAD

**Issue by frideo** [irontec/sngrep#276]
[crash5b.pcap.gz](https://github.com/irontec/sngrep/files/3408141/crash5b.pcap.gz)

sngrep 1.4.6 crashes when opening this 5-packet pcap file, which contains one SIP request and four equal (partial) SIP responses over TCP.
If one packet is removed from the pcap, then the crash does not happen.

Using a SIP server in docker and capturing on the host (without specifying an interface), it's common to see replicated packets; eventually/randomly sngrep crashes with error
***** stack smashing detected ***: <unknown> terminated**

This file has been tested (and crashes) in versions 1.4.5 and 1.4.6 in Ubuntu but does not crash version 1.4.2 in Debian 9.

**Comment by Kaian** [comment]
Hi @frideo 

Thanks for reporting and the sample data, it really helps a lot.

The problem was that sngrep was assuming the body contents of a SIP packets ends with \r\n. There are some cases while parsing TCP that this does not happen (like in fragment retransmission). I have fixed the buffer overflow and improved the SIP packet validator to only handle full SIP packets, ignoring the rest. With this new criteria, your pcap has now only one SIP valid message.

Regards and thanks again!

**Comment by frideo** [comment]
Thanks for the feedback. I've worked in support for years, so I know how valuable some data can be. I'm glad now that I put the effort into finding the exact packets (from a huge file) that caused this.
Thanks for fixing it, too.
