### ISSUE TITLE
Set large packet size

### ISSUE THREAD

**Issue by illyac58** [irontec/sngrep#284]
Hi,
Noticed that sngrep cannot capture in live mode SIP packets larger than 1514 or even reassemble fragmented UDPs, but it can display, if dialog captured by tcpdump. Is there any configuration I can apply to increase the default packet size or enable live reassemble?

**Comment by Kaian** [comment]
Hi @illyac58 

The max snapshot len is set to 262144 bytes defined [here](https://github.com/irontec/sngrep/blob/master/src/capture.h#L88) 

The max packet len is set to 20480 bytes defined [here](https://github.com/irontec/sngrep/blob/master/src/capture.h#L86). That's also the max assembly size and max SIP payload size.

The implented logic to assemble IP is far from good, but we have been able to assemble multple IP fragments into a single packet, greater than 1514 bytes

The logic used to parse a packet is the same for online and offline packets, so the problem seems to be elsewhere. Maybe the amount of traffic is so high that some packets are not being parsed fast enough and are overflowing the libpcap application buffer? In that scenario (that doesn't happen in offline pcaps), some packets could be skipped and assembly will fail.

Regards
