### ISSUE TITLE
Displaying captured HEP data from pcap file

### ISSUE THREAD

**Issue by denyspozniak** [irontec/sngrep#293]
Hello!
I am collecting HEP v2 packets via tcpdump and would display SIP call-flow diagram using **sngrep**, but it shows nothing.

```tcpdump -i lo port 9060 -w /home/sngrep/hepv2.pcap```
```sngrep -I /home/sngrep/hepv2.pcap```

**Comment by idbennm** [comment]
Think this may be same issue as we were seeing possibly?

https://github.com/irontec/sngrep/issues/270

**Comment by denyspozniak** [comment]
As I see it is not. The question is how to display SIP call-flow from HEP pcap file.

**Comment by Kaian** [comment]
Hi,

Current version of sngrep only supports TCP/UDP SIP packets, so payload encapsulated in HEP is not parsed from pcap file or captures from devices using libpcap.

I'm working in my spare time on a new version that will support that, but sadly I have not release date because I'm quite busy these days.

I will keep this as a feature request.

Thanks!

**Comment by Kaian** [comment]
This should be possible since above Pull request was merged. It only supports HEPv3 and you must add `-E` flag to command line to parse HEPv3 data.

Regards!
