### ISSUE TITLE
CentOS 7 update

### ISSUE THREAD

**Issue by voztovoice** [irontec/sngrep#299]
Hello,
from yesterday all my CentOS 7 Servers when trying to update sngrep:

**Package sngrep-1.4.6+20200226.18+09f00ce-0.el7.x86_64.rpm is not signed**

Thank you.

Regards

**Comment by Kaian** [comment]
Hi voztovoice,

In #295 we recreated the rpm packages for Centos 7 and 8 with a new version format.

I have reverted the changes for Centos 7 because I'm not quite happy with the result.
The available version should be again `1.4.6-0.el7` that should not cause problems with signature.

Thanks for reporting!
