### ISSUE TITLE
TLS 1.2 I see no traffic

### ISSUE THREAD

**Issue by mase2hot** [irontec/sngrep#303]
Hi,

When running 'sngrep -k /path/to/privatekey.pem' I see no traffic. I can see my Kamailio sending options in its own log, but these are not seen in sngrep. How can I get this working?

Thanks

sngrep --version
sngrep - 1.4.6
Copyright (C) 2013-2018 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with GnuTLS support.

Written by Ivan Alonso [aka Kaian]

**Comment by Kaian** [comment]
Hi @mase2hot 

Most probably a duplicate from #256 and #214 

Currently only two ciphers are supported. (check #59)
Also, sngrep must capture the initial SSL handsake in order to get the SSL session data (is not possible to decrypt starting sngrep after the connection has been established).

You can check the used cipher in ServerHello message using ssldump, wireshark or other tool.

Thanks for reporting!

**Comment by mase2hot** [comment]
The issue I believe was due to diffie hellman, which is a shame as it means Sngrep can never be used when trouble shooting Microsoft Teams direct connect.

**Comment by Kaian** [comment]
If DH is used then it's not possible for any capture tool to decrypt the data, no matter it has the key or not.

Softwares usually provide alternative debugging methods like HEP sending or PCAP dumping, but I have no idea of Microsoft products.

Best regards!
