### ISSUE TITLE
Help request: decode TLS call 

### ISSUE THREAD

**Issue by cedricbeip** [irontec/sngrep#347]
Hello, 

I'm trying to use sngrep in realtime to debug Opensips configuration.
I'm using tls. 
I tried ` sngrep -k /path/to/private_key`, I see non-encrypted traffic but I can't see any tls packet. 
The algorithm to generate the key is `RSA2048`, the cipher used by the server is `AES128-GCM-SHA256`.
Can you tell me if there is something wrong with the way I use sngrep ? Is this cipher is supported by sngrep ?

thank you in advance for your help.

**Comment by Kaian** [comment]
Hi @cedricbeip 

Sorry but that cipher was not implement. SSL decrypt support was something experimental and only a couple of ciphers were added.

https://github.com/irontec/sngrep/blob/333ce04ce4aedd264a72db45a67a88a4e0b6eabc/src/capture_openssl.c#L42-L48

You can try with any of the listed ciphers, and also be sure to be capturing before the connection is established, because handshake packets contain required data.

Regards!

**Comment by cedricbeip** [comment]
Thank you for your answer @Kaian. 
I'll try this. 
Regards,
