### ISSUE TITLE
Not able to save SIP + RTP trace

### ISSUE THREAD

**Issue by ketan-kothari** [irontec/sngrep#351]
I have pcap file where sip + RTP available which taken using tcpdump.

But when i trying to save specific leg of call using F2 save getting (-) .pcap (SIP + RTP) on popup.
i can successfully able to save only SIP.

![image](https://user-images.githubusercontent.com/30174460/113680461-7e409580-96de-11eb-8be5-48c4b54f8dd4.png)

I open file using sngrep -I command.

Is there any way to save call with SIP + RTP ?

**Comment by Kaian** [comment]
Hi @ketan-kothari 

In order to save RTP packets, sngrep must first capture them by using `-r` command line flag.
Take into account that RTP packets require more memory that just SIP so be carefull on heavy loaded environments.

Regards

**Comment by ketan-kothari** [comment]
So you mean if sngrep capture RTP that time only we can save that ?
I have captured RTP using tcpdump after i opened that pcap file using sngrep  -I so that will not save option for RTP.

Yes exploring in demo system  not in production.

**Comment by Kaian** [comment]
When adding `--rtp` or `-r`  option to command line, sngrep will store RTP packets in memory so you can save them later. Otherwise, the RTP packets are displayed in Call Flow but not stored, making them impossible to save using that screen.

The only case RTP packets are saved without being stored in memory is that you use `-O` command line to save all captured packets.

Regards!
