### ISSUE TITLE
sngrep BPF error

### ISSUE THREAD

**Issue by daxiondi** [irontec/sngrep#356]
sngrep version 1.4.8
When I use sngrep command to capture,
I can get the corresponding session of invite. 
When I use `sngrep port 32766` or `sngrep portrange 32766`
I can only capture the options session, and invite is lost

**Comment by daxiondi** [comment]
@Kaian Could you help me?

**Comment by Kaian** [comment]
Hi @daxiondi 

Probably your INVITE message is big enough to be fragmented in multiple packets.
When a IP packet is fragmented, the UDP or TCP header is only present in the first fragment, so filters like `port 32766` only match the first one. If the message is incompleted, sngrep won't display it.

Have you tried with other tools and the same bpf filter ? If the problem is fragmentation, then ngrep or tcpdump will only display the fist fragment when filtered with port 32766.


Regards

**Comment by buzhaodi** [comment]
@daxiondi I have also encountered that in the case of multiple network cards, if the network card is not specified, the captured packets will be duplicated. Sngrep is also not displayed at this time. I discarded the duplicate packets in capture.c. Then solved。大兄弟，你的英文和我一样。一看就知道是中国人哈哈
![image](https://user-images.githubusercontent.com/16113837/117953655-d22b4380-b348-11eb-992c-a53dac7abdfa.png)

**Comment by daxiondi** [comment]
@buzhaodi 
hi daxiondi 我试过指定网卡，也不会有invite数据包，不过还是谢谢你。

**Comment by buzhaodi** [comment]
@daxiondi You can try to use tcpdump to specify the port and then capture the packet, and then use wireshark to open it to see if it can be parsed as sip. If it doesn't work also, it is sub-packet.That sngrep definitely can't display

**Comment by daxiondi** [comment]
@Kaian When I use tcpdump, I can get the packet of invite
```
tcpdump -i eth0 port 32766 -w sip.cap
```
Regards

**Comment by daxiondi** [comment]
> @daxiondi您可以尝试使用tcpdump指定端口，然后捕获数据包，然后使用wireshark将其打开以查看是否可以将其解析为sip。如果它也不能正常工作，那就是子数据包。该sngrep肯定无法显示

It's normal to use tcpdump

**Comment by Kaian** [comment]
Can you send me a sample pcap with a single dialog not displayed when using port filter?

**Comment by buzhaodi** [comment]
sngrep -I sip.cap,is work?if can't work,upload your .cap

**Comment by daxiondi** [comment]
```
sngrep -d eth0 -O save.pcap port 32766 and udp
```

[save.pcap.zip](https://github.com/irontec/sngrep/files/6465344/save.pcap.zip)

**Comment by buzhaodi** [comment]
Please use tcpdump to capture packets....because sngrep can't Parsing。。。

**Comment by daxiondi** [comment]
[sip.pcap.zip](https://github.com/irontec/sngrep/files/6465455/sip.pcap.zip)

**Comment by buzhaodi** [comment]
As you said, it is indeed fragmented in multiple packets，Modify sngreprc, "set capture.buffer 20" and try。or Modify the source code setting.c  var capture.buffer is 20.If it still doesn’t work, I don’t know what to do

**Comment by daxiondi** [comment]
> 如您所说，它确实是分成多个数据包，修改sngreprc，设置“ set capture.buffer 20”，然后尝试。或者修改源代码设置。cvar capture.buffer为20。如果仍然不起作用，我不要不知道该怎么办

Thank you for your advice, I tried this option, but I was unlucky.

**Comment by Kaian** [comment]
Hi, the second zip you have atached does not contain a valid .pcap file, according to file command is just data.

If I understand correctly, the problem is that using `sngrep -d eth0` you can see traffic that is not displayed using `sngrep -d eth0 port 32766 and udp`, right? Please attach a capture generated with `sngrep -d eth0 -O sngrep-full.pcap` **that contains an invite** that is displayed when you run `sngrep -I sngrep-full.pcap` but not when you run `sngrep -I sngrep-full.pcap port 32766 and udp`.

Regards

**Comment by daxiondi** [comment]
This is `sngrep -d eth0 -O sngrep-full.pcap` command capture packets.
[sngrep-full.tar.gz](https://github.com/irontec/sngrep/files/6469984/sngrep-full.tar.gz)
Regards

**Comment by Kaian** [comment]
Hi!

Sorry but the attachment you provided doesn't look like a pcap capture, I'm getting this.

```
~ $ tar xzvf sngrep-full.tar.gz 
sngrep-full.pcap
~ $ file sngrep-full.*
sngrep-full.pcap:   gzip compressed data, last modified: Thu May 13 02:12:28 2021, from Unix, truncated
sngrep-full.tar.gz: gzip compressed data, last modified: Thu May 13 02:12:41 2021, from Unix, original size modulo 2^32 10240

~ $ sngrep -I sngrep-full.pcap 
Couldn't open pcap file sngrep-full.pcap: unknown file format

~ $ mv sngrep-full.pcap sngrep-full.pcap.gz
~ $ gunzip sngrep-full.pcap.gz
~ $ file sngrep-full.*
sngrep-full.pcap:   data
sngrep-full.tar.gz: gzip compressed data, last modified: Thu May 13 02:12:41 2021, from Unix, original size modulo 2^32 10240
```

**Comment by daxiondi** [comment]
This is my command 
```sngrep -d eth0 -O sngrep-full.pcap```
Is the captured file an error caused by a problem with the format of the captured file? 
Consider fixing this problem?

**Comment by Kaian** [comment]
Sorry but so far we didn't yet find a problem in sngrep. The behaviour you're describing may be how BPF filters work in all libpcap applications so nothing we can actually fix in sngrep. I request the pcap because I'm curious how the sip packets that you're handling are.

Please, send me the original sngrep-full.pcap file to kaian@irontec.com without compressing.

Regards!

**Comment by daxiondi** [comment]
Thank you for your reply. I've sent an email
Regards!

**Comment by Kaian** [comment]
Hi @daxiondi 

I have debugged the pcap file you sent me and in fact this is a common IP fragmentation problem. The INVITE message is split into multiple packets and not all of them matches `port 32766` filter.

If you want to capture all the traffic, you must include all IP fragments in the filter.

     sngrep -d eth0 port 32766 or 'ip[6:2] & 0x3fff != 0'

Regards,

**Comment by daxiondi** [comment]
That's right. I just want to know the reason. Thank you for your answer.
