### ISSUE TITLE
can't display sip msg when use BPF if pkt Subcontract.

### ISSUE THREAD

**Issue by buzhaodi** [irontec/sngrep#357]
dear @Kaian,I found the problem that was closed today #356. In the end, the reason why it is not displayed is that the invite message is too large.i get  pcap， if I use “sngrep -I 111.pcap“. It can be displayed normally, if "sngrep port 5060 -I 111.pcap“ is used, it is abnormal。I found that if the port is specified, the parse_packet function will only be called once. However, there are two packets in the captured packet, resulting in incomplete display.
For some reasons, the packet capture cannot be made public。
But the thing is like this. After that I used tcpdump to do the same operation, "tcpdump -B 409600 port 5060 -r 111.pcap -w 333.pcap" and found that 333.pcap is also incomplete. So this is not the problem with libpcap except
@daxion

**Comment by Kaian** [comment]
Hi, the problem was closed by the reporter, I think by mistake.

After some emails @daxiondi was able to sent me a valid pcap file that in fact shows the INVITE is split into two fragments. Only the first fragment has UDP header, son only the first fragment have port (because port is part of the UDP header). The second fragment has no port data so libpcap does not send it to sngrep (the parse_packet function).

 If you want to capture all the fragments you must use a BPF filter that can consider all pieces:

    sngrep -I 111.pcap port 5060 or 'ip[6:2] & 0x3fff != 0'

Being the same problem, it's better to continue in the original issue, so I'm closing this.

Regards
