### ISSUE TITLE
Show call duration and number of results for search

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#37]
Another request for a new features (two of them), based on what I find useful by using more and more sngrep.

### First one

It would be nice to see the duration of of the call as another column in the main view. Typically one wants to look at those calls that are very short, could be an indication that an ACK was misrouted or there was a codec mismatch.

I think that there can be two interesting values:

* 1) duration between first request of the dialog and the last - good for canceled calls to see how long the user was waiting or for calls not completed due to timeout (e.g., gateway not reacting)
* 2) duration between 200ok of the first INVITE and the BYE request (or the reply to the BYE)

It could be a single column, showing the value for 1) for all calls (dialogs), adding 2) in parenthesis for completed calls. For example, a canceled call after 20 seconds will show:

```
20
```

An answered call after 15 seconds of ringing and 60 seconds of talk will show:

```
75 (60)
```

I guess the values can be easily computed when setting the final state: REJECTED, CANCELLED or COMPLETED. Makes no sense to print and update in real time for IN CALL dialogs.

### Second one

In the main view, when searching with F3, would be good to see the number of how many calls were matching. I haven't seen a status bar where it could be shown, maybe after the text in the search input field ... 

As an example of usefulness: have the trace of the past day, then search for calls made by user ABC and see how many are there.

Thanks again for you time and the nice, very useful tool!

**Comment by Kaian** [comment]
Hi!

 First the second one :D

 I have added a field in the first row, after the Current mode (which has a known max size).
 It will display call count (so you know when call limit has reached) and matching entries count. This matching count only works with display filter right now (the F3 one). I don't want to implement the other available filter options becase I feel all the matching stuff code must be unificated and rewritten.


About the first one.
A new attribute duration won't be hard to code. I have some doubts about the output. I like your suggestion about using one column for both data, but I'm thinking of a call of 12 minutes with 15 seconds ringing. In that case wouldn't be better to show `12:40 (+15)` (Call Duration + Establishment) or `12:40 (12:25)` (Full Duration + Call Duration) rather than `940 (925)` (Full Duration + Call Duration)?

By the way, I've been in a refactoring hype, so master have lots of code modifications. Sorry in advance for using you as testers in case I've broken something.

**Comment by miconda** [comment]
Thanks, quite fast coding, some beers on me if we get the chance to meet (next week in BCN?).

For one, indeed, you suggestion with min:sec is better for human reading. All of the variants you proposed are ok for me, as long as I can determine all duration (from first to last message of the call) and effecting on-call duration (from answer to the termination of the call), choose what you think is better.

**Comment by Kaian** [comment]
Heh, thanks. I'm from Bilbao but maybe someday in one of those VoIP meetings my Irontec coworkers use to go :beer: :)

I have changed my mind so I've added two new columns. The reason for splitting the information is that I'm thinking about a way to sort columns in the future, so I could be confusing while ordering a field with two values. I'll also add a different value for attribute Title and Description so Column Select panel will display _Conversation Duration_ instead of _ConvDur_.

I'm also working improving the performance with more messages (2000 limit is a bit _meh_ while working with big pcap files), and I have detected the matching count as a problem: It evaluates every single call stored. I must think a way to improve this, because in fact I use that counter to properly draw the scrollbar.

Just in case, would be fine for you if matching count displays something like (1000+ matches) or it's really important the exact number of matches?

Thanks for the feedback!

**Comment by Kaian** [comment]
Nevermind, I found proper ways to handle filtered entries.
Thanks!

**Comment by miconda** [comment]
Thanks again, works fine for me with two columns. Maybe it's time to visit Berlin for good :beers:.

I would like to see the exact number of matches, rather than estimations like 1000+. Maybe from a higher number like 10 000 or 100 000, but 1000 calls quite usual number of calls for even 1 hour of a sip trace.

**Comment by Kaian** [comment]
I've been reworking all the filters logic to merge them and make more efficient. Also, adding new filters to the filter panel (anyone use that?) will be easier in the future.

With the changes, It should be possible to handle more than 50000 calls, filter them, and move around the list with a 2-3 delay in feedback (that was the cause there was a soft-limit of 2000). 

The filtered amout will be exactly shown, like it was previously. There is also a new option in save dialog that let you save filtered dialogs to a new pcap file.

Some things may have broken, but overall I think performance has improved a lot.

Thanks!
