### ISSUE TITLE
Delay when viewing a flow on a host with a large number of interfaces

### ISSUE THREAD

**Issue by nborisenkov** [irontec/sngrep#377]
I have a problem with viewing flows on a server with a lot of interfaces (about 600 PPP interfaces). Immediately after starting, new flows are displayed as usual, but when you try to view more detailed information of any flow, there is a delay (about 70 seconds). Any subsequent attempts to view this or any other flow occur without delay.

Launch:
`strace -o sngrep.strace.output -tt -ff sngrep -d eth0.157`

In the strace output, I noticed the timestamps 15:30:02.995376 and 15:30:03.297091

I have replaced some real IP addresses in strace output

Is there any way to avoid looping through all interfaces when viewing any flow for the first time?

sngrep version 1.4.9 (installed from http://packages.irontec.com/debian)
Kernel version: 5.2
Debian 10 (buster)

[sngrep.strace.output.17260.gz](https://github.com/irontec/sngrep/files/7252058/sngrep.strace.output.17260.gz)

**Comment by Kaian** [comment]
Hi @nborisenkov 

While displaying the flow screen, sngrep checks if column addresses are local to the current machine in order to highlight them  to make easier the process of identifying current host when capturing online.

This is normaly a fairly fast process with small number of interfaces, but when checking a not local ip against 600 interfaces (matching none of them) can be a bit more costly, taking into account this is done every screen refresh.

You can disable this feature in configuration by adding this line in your ~/.sngreprc or /etc/sngreprc file

```
set cf.localhighlight off
```

and check if that improves the performance.

Regards!

**Comment by nborisenkov** [comment]
Thanks, it helped. Now the delay is gone.
