### ISSUE TITLE
IPv6 SIP traffic completely ignored

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#38]
hi,

whatever I tried, I couldn't make sngrep display IPv6 SIP traffic. Looks like it's explicitly sniffing to IPv4 traffic only, even if I put ipv6 expression as capture filter.

**Comment by Kaian** [comment]
Hi @ssinyagin 

Right now sngrep only supports IPv4. It wont be hard to implement packet capture for IPv6 but.. It has great impact in Interfaces. IPv4 addresses have a max length of 15 characteres and IPv6 addresses are quite longer... I thought about this problem some time ago and maybe a solution will be to implement a two line column header for the flow view.

Addresses also appear in call list (no problem here tho), and in arrow messages when "First SPD address" of payload is printed.

I'm not used to work with IPv6 addresses, but I assume full address should be printed.

**Comment by ssinyagin** [comment]
ipv6 address is actually variable length, because it allows to shorten the sequence of zeros.

I agree, displaying it is a bit of a problem :)   
Maybe a command-line switch which tells sngrep to use wider columns for addresses?

**Comment by Kaian** [comment]
It seems the max length for IPv6 is 46 (as defined by `INET6_ADDRSTRLEN`). 

Wider columns for the list are not a problem, but for Flow display columns will be too separated each other... In order to keep the arrow lenght, It will be required to have headers with three rows and split the address (not sure if thats a good idea).

Right now the less impact _compatibility_ implementation is to cut the address to the fist 15 characters. I don't know if that may result as easy as useless.

**Comment by ssinyagin** [comment]
I think last 15 characters would be more informative. Maybe put two dots in
front, and then 13 last characters (in case if the address is longet than
15 symbols)

**Comment by Kaian** [comment]
I don't have a testing enviroment with IPv6 enabled :|
Would you mind to send me a pcap capture from tcpdump or ngrep of some IPv6 SIP dialogs.

Thanks in advance.

**Comment by ssinyagin** [comment]
sure, will do. I can also let you in onto my test server

**Comment by Kaian** [comment]
Hi @ssinyagin 

  `ipv6` branch has an initial approach to support IPv6. It prints both IPv4 and IPv6 dialogs, with short IPv6 addresses (last 15 chars).

  You should need to run `./bootstrap.sh` and enable IPv6 using `--enable-ipv6` flag of configure script.

**Comment by ssinyagin** [comment]
did you choose not to use ".." in front of a cut-off ipv6 address?

The rest is fine so far, with some minor quirks: 1) I get a f*ck sign during ./configure; and 2) why not setting "set background dark" as default?

**Comment by Kaian** [comment]
Oh, I forget about the leading dots! , I'll do in the next commit :)

I don't get the 1) one :open_mouth:  Maybe I broke something in configure template.

About the 2) one, that's because some terminals show a _grey_ background If I explicit set background color to _black_ but It displays a nice black if I use _default_ colors.   'dark' background setting is a workaround. The real good improvement will be handle default terminal colors (don't set any background or foreground) and being able to display everything perfectly. I add it to the TODO list :D

Thanks for the testing!

**Comment by ssinyagin** [comment]
#1 was about your company logo. It really looks like a finger :)

**Comment by Kaian** [comment]
Hahhaa, I will share that feeling with my boss :laughing: 

I guess I should remove that logo or improve my ascii art skills :joy: :joy: :joy:

**Comment by Kaian** [comment]
No more _fuck you sign_ anymore in `master`. Now there is a awful publicity banner 0f8f14b667987aced027982a10d7ac58d67c3fd5
You can also complete disable the logo if it's too disturbing :joy:

**Comment by Kaian** [comment]
After thinking a bit, I've done as you suggested and now `set background dark` is set by default in 6b6967679e65ecdd213397c5fbe5a54a0874356f.

Users can still use `set background default` to use the default foreground and background of the terminal (if any).

**Comment by Kaian** [comment]
IPv6 traffic should not be ignored anymore, but IPv6 addresses display require more work in the future.

This changes has been merged to `master`
