### ISSUE TITLE
Additional Keybindings: Support and Documentation

### ISSUE THREAD

**Issue by ooglek** [irontec/sngrep#41]
I happened upon the single keystroke action support in the Help menu that are alternates for the Function keys highlighted in the status bar in the bottom of sngrep. I'm very used to tools such as bash, less/more and vim and would love to see additional keybindings available in sngrep.

1. SIP Messages Flow Viewer, Raw Viewer
  1. CTRL-f = Page Down (less/more)
  1. CTRL-b = Page Up (less/more)
  1. CTRL-d = Page Down half window (less/more)
  1. CTRL-u = Page Up half window (less/more)
  1. k = Down Arrow (vim, less/more)
  1. j = Up Arrow (vim, less/more)
1. Filter Dialog Box Text Inputs (SIP From/To, Source, Destination), Filter Display Input
  1. CTRL-u = Delete input (bash)
  1. CTRL-a = Move cursor to start of the input field (bash)
  1. CTRL-e = Move cursor to the end of the input field (bash)

A good overview of Bash keyboard shortcuts can be found here: http://ss64.com/bash/syntax-keyboard.html

Some less keyboard shortcuts: http://ss64.com/bash/less.html

An additional request would be to allow sngrep to show the single character keybindings in the hint bar at the bottom of the screen for those who are less function-key inclined.

**Comment by Kaian** [comment]
Hi @ooglek, thanks for reporting!

Adding new keybindings won't be hard. I must research a bit for Ctrl modifiers, and update existing ones.

I would be nice to make keybindings configurable using sngreprc file, and allow multiple binds for the same action, but that will require a bit more time to develop and documment properly.

**Comment by Kaian** [comment]
I've added the suggested keybindings and tested with xterm and guake terminals.
Feel free to test and reopen if I have missed any of them or they are not working as expected :)

**Comment by Kaian** [comment]
Just a note. Right now, sngrep does not scrolls lines based on available terminal lines (which in fact will be the correct thing to do), but uses a configurable option to determine how many steps must be done with each NPAGE and PPAGE keys.

This configuration options are `cl.scrollstep` and `cf.scrollstep` for Call List (Main screen) and Call Flow screens. For half window scroll keybindings I've halved that value (insted of window available lines). 

I consider using available screen lines for page moving a different enhancement or bug fix.

**Comment by Kaian** [comment]
Hi @ooglek 

I've recoded all key handling functions to process actions instead of key themselfs. This way, for example, any screen that uses UP or DOWN keys to move arround will allow using your suggested bindings (j, k). IN the future redefining a key will have impact in all screens where that action can be handled.

I've also added a not yet documented configurable option (`hint_key_alt`) that can be set to `on` in sngreprc file to display the second binding to each action of the bottom bar. You can also toggle this option at runtime using the default binding `K` (uppercase).

This is a big change and maybe some actions are broken, so all testing and feedback will be appreciated. We're a step closer to allow user configurable keys :)

Thanks for all!
