### ISSUE TITLE
reassembled sip packet

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#422]
hi kaian 

can sngrep  capture reassembled sip packets and show in call flow panel

**Comment by RodolfoCDSantos** [comment]
Hi sajai20.
When you mean reassembled SIP packets. Are you talk about to merge pcaps to see in flow panel?

**Comment by sajai20** [comment]
no @RodolfoCDSantos in single pcap if we have fragmented tcp messages can sngrep show's that message in call flow panel

**Comment by RodolfoCDSantos** [comment]
Hi @sajai20!
I don't think there's anything in the code to analyze packet losses or SIP SIG fragmentations. If you were talking about RTP, you could make a comparison by subtracting the amount of RTP packets sent, versus the packets received (the packet quantity information is presented in the RTP arrows). But you're talking about SIP SIG (TCP), which is a very small volume of packets for each protocol state. And in these cases there would be retransmission, what you would notice, would be the delay between one state and another and this is already presented in the first column of the call flow (ladder diagram). @Kaian  please correct me if I'm talking nonsense.

**Comment by Kaian** [comment]
Hi!

Sorry for the late response, I'm currently on holidays :)

I think what @sajai20 refers is just TCP fragmentation. Yes, sngrep is able to asseble IP segments and TCP fragments, but for TCP there are some limitations: fragments must be received in order and without retransmissions, otherwise assembly may fail.

Also, for IP assembly, take into acount that BPF filters like "port 5060" may skips the segments after the first one, because only the first one contains a header with port (UDP or TCP).

Regards
