### ISSUE TITLE
Not Capturing TLS packets 

### ISSUE THREAD

**Issue by Sivasundareswaran** [irontec/sngrep#444]
**Hi Everyone ,**

I'm using sngrep  1.7.0 and configured with openssl ,but I am unable decode SIP over TLS packets ,can you please advise how to capture those SIP over TLS packets 

I used the below  commands 
sngrep -k <pem_file_path>

Thanks

**Comment by Kaian** [comment]
Hi @Sivasundareswaran 

sngrep only support a couple insecure cipthers (TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA and TLS_RSA_WITH_AES_256_GCM_SHA384), and needs to capture the initial TLS negotiation in order to decrypt the conversation. If you're using TLS v1.2 or greater with a DH or ECDH cipher, decrypting is impossible as these ciphers implement Perfect Forward Secrecy.

I have added a [FAQ](https://github.com/irontec/sngrep/wiki#frequent-asked-questions) entry with this topic.

Regards!

**Comment by Sivasundareswaran** [comment]
is the below cipher is supported ?
TLS_AES_256_GCM_SHA384

**Comment by Kaian** [comment]
Nope. [TLS_AES_256_GCM_SHA384](https://ciphersuite.info/cs/TLS_AES_256_GCM_SHA384/) with code 0x1302 is not in the above list, so it's not supported.

https://github.com/irontec/sngrep/blob/master/src/capture_gnutls.c#L42-L48
