### ISSUE TITLE
Implement packet reassembly

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#50]
issue for cap packet more 4096 bytes . 

i had sent pcap file .

**Comment by Kaian** [comment]
Hi michael

Right now sngrep does not support reassembly fragmented packets, so I consider this an enhancement. It's also included in TODO list :)

    capture:
    * Handle Packet fragmentation
        Right now capture process only handle packets with SIP payload,
        so if a packet is marked as fragmented, part of its payload
        will not be displayed.

Thanks for the test pcap file!! It has a SIP message splitted into 4 fragments.

**Comment by Kaian** [comment]
This issue should be fixed in `master` branch.

Take into account that preview panel to the right of call flow may not display all the payload of the packet. You can press `Enter` to see the full packet payload or use the Call Raw panel (pressing `r`). That views accept moving arround with Arrow keys.

This may introduce another enhancement to have some keybindings for moving the preview payload up and down. Sadly, arrow keys don't accept modifiers (neither shift, alt or ctrl), so I must think about other candidates.

Thanks for reporting and the test file!
