### ISSUE TITLE
Segmentation fault issue when track with second ACK

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#51]
Segmentation fault issue when track with second ACK

**Comment by Kaian** [comment]
Hi michael!

Thanks for reporting and the test pcap :)

The problem was related with RTP packets encoding. We only show standard RTP formats (from 0-34) and the sdp in the dialog you sent me had 104 H264/90000. One of the enhancements I must do is to use SDP formats ids to detect RTP formats... for the next relase :)

Anyway, `master` should not crash anymore :D
