### ISSUE TITLE
crash when call flow with codec silk .

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#56]
crash when call flow with codec silk .
i had sent mail with crash.pcap

**Comment by Kaian** [comment]
Hi @michael2009 

This crash also seems fixed in the latest `master` commits.
Now sngrep won't crash but RTCP is being displayed as RTP with (Unassigned codec).

Parsing RTCP will be a nice addtion that can provide information about call quality but I consider it an enhancement to add to TODO list.

Thanks for reporting and pcaps !

**Comment by Kaian** [comment]
This should be fixed in 0.4.2
