### ISSUE TITLE
add GnuTLS support

### ISSUE THREAD

**Issue by zabbal** [irontec/sngrep#68]
OpenSSL does not only have BSD license contrary to this project, it's also well known for huge amount of deadly security vulnerabilities, even before heartbleed.

It would be nice if I could avoid bringing in such a library just because of sngrep - having support for GnuTLS will let the user to make such a choice.

**Comment by Kaian** [comment]
Hi @zabbal ,

This is something I'm quite interested and I think about moving to GnuTLS every time I work with OpenSSL functions. I prefer changing from OpenSSL to GnuTLS rather than making the code compatible with both. This way we could keep sngrep totally GPL'd (instead the dual license we are keeping now when compiled with ssl enabled), which most probably will make most users/distributions/stallman happier.

Anyway, the change won't be trivial. The configuration flag should change to `--with-gnutls` which will trigger a new major version (2.x.x) due to incompatibilities (or keep 1.x.x with both ssl library for a while). 

We don't use TLS a lot, so any other feedbacks will be appreciated related to this library change.

Thanks!

**Comment by zabbal** [comment]
I completely agree that transition is better than supporting both. Probably a good starting point would be http://www.gnutls.org/manual/html_node/Compatibility-with-the-OpenSSL-library.html

**Comment by Kaian** [comment]
Hi @zabbal ,

The `gnutls` branch has version of sngrep with OpenSSL functions replaced by GnuTLS ones in case you want to give it a try.

You must re-run `./bootstrap.sh` and use `--with-gnutls` flag to enable TLS decrypting (which now requires gnutls, gnutls-openssl and libgcrypt). 

The branch will be deleted someday, when we (or the community) decide that it must be merged with master or discarded.

I highly appreciate any feedback regarding this change.

**Comment by Kaian** [comment]
Just FYI, the code uses abscract key types functions [1] so, right now it seems only compatible with gnutls v3

[1] http://www.gnutls.org/manual/html_node/Abstract-key-types.html

**Comment by Kaian** [comment]
I have decided to merge the branch in master and make both decrypt modes available until the next major release (2.x.x), when probably we'll drop OpenSSL compatibility.

For now, I give the opportunity to choose the ssl library in 1.x.x, while I'll test GnuTLS in multiple distributions. 

Thanks for your feedback and suggestions!!

**Comment by jungle-boogie** [comment]
Have you considered using libressl?

**Comment by Kaian** [comment]
Umm, no, I haven't.. yet!.

I would like to make sngrep dependencies as minimal and generic as possible.

Most people have libpcap and ncurses installed in their systems (ngrep, tcpdump, top and many other tools use them) and probably openssl and/or gnutls. LibreSSL could be a good replacement for OpenSSL support, but I don't want to pull any dependencies while installing binaries. That's mainly the reason I dont use sip parsers or curses widgets (both will make my life easier for sure).
If lots of users have libressl as their main ssl library we could consider it.

Feel free to join #sngrep at freenode for any discussion and suggestion :)

**Comment by Kaian** [comment]
After some tests and chit-chat at IRC channel it seems the source is already compatible with LibreSSL without changes.

But It will be nice to have an option in configure script to specify where the SSL libraries are (in case you prefer one SSL library over the other when installed both on the system).

Thanks to @jungle-boogie and sorry for totally changing the Issue topic ;(
