### ISSUE TITLE
Feature Request:  Align Directional Arrows with Timestamp

### ISSUE THREAD

**Issue by kismetgerald** [irontec/sngrep#75]
Good-day,

I have noticed that when __*"Show SDP information in messages"*__ is set to _first_ or _full_, the directional arrows in the Call Flow window don't line up with the time stamps.  Specifically speaking it appears the rendering of the additional SDP information causes the an offset in alignment.  Perhaps it would be a good idea to align the two elements at the bottom border so they stay aligned.

I believe this will make for better readability of the packets and make analysis a bit easier.  Thanks again for a great product.
![snap 2015-11-19 at 06 14 03](https://cloud.githubusercontent.com/assets/14914151/11269680/74c7f6a8-8e86-11e5-9fc4-7594d4bc09e7.png)

**Comment by Kaian** [comment]
Hi @kismetgerald!

Umm you seem to have _delta time_ disabled in your configuration.
Delta time shows elapsed time between messages and is displayed below the message timestamp.

In order to align the time with the arrow, I must change the delta display position and logic to put it above the timestamp and show the difference between current message and previous (and not next message what is being displayed right now).

I have little time right now, but I will give it a try as soon as I can :)

Thanks for reporting!

**Comment by Kaian** [comment]
Hi @kismetgerald 

In order to make the timestamp aligned with all arrow types (SIP, RTP and RTCP) I had to change the src and dst RTP/RTCP ports position to avoid overlapping. It will look like the attached image (ports are now displayed in the space between columns).

It's ok for me, but If someone thinks it's too much information for too little space, I appreciate any kind of feedback.

![alignment](https://cloud.githubusercontent.com/assets/800069/11367484/35a30792-92b4-11e5-8415-7abd0327f588.png)

**Comment by kismetgerald** [comment]
@Kaian 

Awesome man...thank you so very much.  When will the update be available in the repo?  I just tried apt-get upgrade but it didn't see any updates.  Or will I have to reinstall?

**Comment by Kaian** [comment]
We have to test a bit before pushing to `master` (a couple of days) to find if there's any problem related to the change.

It will only be available in packages in the next release (probably 1.2.0) where we will join all the pending enhancements and bug fixes (we don't create packages with each commit!). I like to release a lot, even with small changes, so stay tunned.

**Comment by kismetgerald** [comment]
sure, take your time.  Thanks.

**Comment by jungle-boogie** [comment]
Wow, nice work, @Kaian!

**Comment by Kaian** [comment]
Thanks!!

Btw, all this changes will be in `develop` branch while we test them, in case anyone is compiling sngrep from the git clone. The branch will be merged and deleted soon, tho.

**Comment by kismetgerald** [comment]
Thanks @Kaian
