### ISSUE TITLE
Save currently displayed call flow to txt file

### ISSUE THREAD

**Issue by dunst0** [irontec/sngrep#77]
I would like add a feature request it would be nice to save the currently displayed call flow to a text file.

**Comment by Kaian** [comment]
Hi @dunst0

Not sure if there is an easy way to dump ncurses displayed screen to a file. I havent seen that in another curses program.

The problem here is that flow display is designed for its window and its not printed line by line (like a textfile would be), so Its not something I could implement whitout duplicating all the code.

Also, I never enabled mouse in sngrep to make users able to select and copy screen contents and paste to a file or whatever.

Sadly this is something that requires redesign of flow window but I will keep in mind as a desired feature.

Thanks for the feedback!!
