### ISSUE TITLE
RTCP / Homer stats

### ISSUE THREAD

**Issue by kevinlong206** [irontec/sngrep#98]
Apologies if this is answered elsewhere,

I understand that newer versions oh "Homer" support showing real-time statistics about SIP/RTP quality,  things like packet loss, jitter buffer, codecs, etc.

Does sngrep have support for sending this (RTCP? ) information to Homer ?

Thank you,

Kevin

**Comment by Kaian** [comment]
Hi @kevinlong206 

Nope!

RTCP still requires some work for sngrep. We try to parse the extended report blocks from RTCP captured packets to show them in RTP arrows preview (cause RTCP arrows will disappear soon), but it doesn't work very well.

I think RTCP is something new to captagent6 and most probably I will _take some ideas_ of their code. After improving the sngrep RTCP parser, most probably I will try to add the support you mention. It it requires JSON dependencies and there's no other way to send those reports, maybe I'll skip this enhancement.

sngrep has support for HEP because is a great protocol supported by multiple SIP tools, proxys, b2b, but I prefer not implementing so may captagent functionalities. They are different tools with different purposes, so I prefer to focus on other improvements and make each tool an expert in their tasks.

Regards and sorry for the long response :)

**Comment by kevinlong206** [comment]
OK Thank you for the information. Still hoping I can get the TLS sniffing working so I can view the SIP transactions and possibly send to Homer but I have not yet figured out what the problem is there..
